services:

  backend:
    build:
      context: ./app
    container_name: newsletter-wizard-backend
    volumes:
      # Mount log file for easier access
      - ./cron.log:/app/cron.log
      - ./backend_logs:/app/logs
    env_file: ".env"

  app:
    container_name: newsletter-wizard-app
    build:
      context: ./app
    env_file: ".env"
    tty: true
    restart: always

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
    depends_on:
      - app
    tty: true
    restart: always